### ISSUE TITLE
Using HTML with jekyll theme

### ISSUE THREAD

**Issue by nathansolomon1678** [nathansolomon1678/programmer-training#6]
I'd like to write more of this in HTML so that we can do more stuff (such as creating quizzes, interactive models, boxes of text off to the side, etc.) while still making it look nice. I writing HTML code directly in markdown, and it didn't appear to work. Also, we could write our own css code to make all th HTML more customizable.

**Comment by EithneA-V** [comment]
I can try to work on that a bit. Let me know what to do for it

**Comment by LyraSolomon** [comment]
CSS isn't a thing you generally write yourself, and Jekyll should do it for you if you set it up right. I will investigate.
